apiVersion: v1
kind: Service
metadata:
  name: ai-centerionware-com-service
spec:
  type: ExternalName
  externalName: ai-agent-text.centerionware.lan
  ports:
  - name: http
    port: 3002
    targetPort: 3002
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: homelab-authentik@kubernetescrd
  name: ai-centerionware-com-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: ai.centerionware.com
      http:
        paths:
          - backend:
              service:
                name: ai-centerionware-com-service
                port:
                  number: 3002
            path: / #Example.
            pathType: Prefix
          - backend:
              service:
                name: auth-forward
                port:
                  number: 9000
            path: /outpost.goauthentik.io/
            pathType: Prefix
  tls:
    - hosts:
        - centerionware.com
        - '*.centerionware.com'
      secretName: centerionware-default
