apiVersion: v1
kind: Service
metadata:
  name: centerionware-service
spec:
  type: ExternalName
  externalName: gitlab.centerionware.lan
  ports:
  - name: http
    port: 801
    targetPort: 801
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: centerionware-pages-default-cert
spec:
  secretName: centerionware-pages-default
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  commonName: "centerionware.com"
  dnsNames:
    - "centerionware.com"
    - "*.centerionware.com"
    - "*.pages.centerionware.com"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: centerionware-ingress
spec: 
  routes:
  - kind: Rule
    match: HostRegexp(`(?i)^(alpine|build|sixcloud|cloud)(?:-(?:(runner|www|kiosk|notes|onboarding|helpdesk|sshkey)))?(.*\.)?centerionware\.com$`)
    services:
    - kind: Service
      name: centerionware-service
      port: 801
    scheme: https
    path: /
    middlewares: 
    - name: alpine-runner-redirectregex
    - name: build-runner-redirectregex
    - name: cloud-runner-redirectregex
    - name: sixcloud-runner-redirectregex
    - name: kiosk-redirectregex
    - name: notes-redirectregex
    - name: onboarding-redirectregex
    - name: runner-redirectregex
    - name: sshkey-redirectregex
    - name: www-redirectregex
  - kind: Rule
    match: HostRegexp(`(?i)^(.*\.)?pages\.centerionware\.com$`)
    services:
    - kind: Service
      name: centerionware-service
      port: 801
    scheme: https
    path: /
  tls:
    secretName: centerionware-pages-default
    domains:                        # [24]
    - main: "centerionware.com"            # [25]
      sans:                         # [26]
      - "centerionware.com"
      - "*.centerionware.com"
      - "*.pages.centerionware.com"
---


