apiVersion: v1
kind: Service
metadata:
  name: ceph-service
spec:
  type: ExternalName
  externalName: pve.centerionware.lan
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: homelab-authentik@kubernetescrd # Optional
  name: ceph-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: ceph.centerionware.com
      http:
        paths:
          - backend:
              service:
                name: ceph-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
          - backend:
              service:
                name: auth-forward
                port:
                  number: 9000
            path: /outpost.goauthentik.io/
            pathType: Prefix
  tls:
    - hosts:
        - "centerionware.com"
        - "*.centerionware.com"
      secretName: centerionware-default
