apiVersion: v1
kind: Service
metadata:
  name: desperate-dev-service
spec:
  type: ExternalName
  externalName: kubernetes.ingress.traefik.centerionware.com
  ports:
  - name: http
    port: 443
    targetPort: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    kubernetes.io/ingress.class: traefik
  name: desperate-dev-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: desperate.dev
      http:
        paths:
          - backend:
              service:
                name: desperate-dev-service
                port:
                  number: 443
            path: /
            pathType: Prefix
    - host: "*.desperate.dev"
      http:
        paths:
          - backend:
              service:
                name: desperate-dev-service
                port:
                  number: 443
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "desperate.dev"
        - "*.desperate.dev"
        - "*.hyperswitch.desperate.dev"
      secretName: desperate-dev-default
