apiVersion: v1
kind: Service
metadata:
  name: license-service
  namespace: homelab
spec:
  type: ExternalName
  externalName: nvidia-licensing.centerionware.lan
  ports:
  - name: license
    port: 443
    targetPort: 443
  - name: grid
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    kubernetes.io/ingress.class: traefik
    # traefik.ingress.kubernetes.io/router.middlewares: homelab-authentik@kubernetescrd # Optional
  name: license-ingress
  namespace: homelab
spec:
  ingressClassName: traefik
  rules:
    - host: license.centerionware.com
      http:
        paths:
          - backend:
              service:
                name: license-service
                port:
                  number: 443
            path: /
            pathType: Prefix
    - host: grid-drivers.centerionware.com
      http:
        paths:
          - backend:
              service:
                name: license-service
                port:
                  number: 8080
            path: /
            pathType: Prefix

  tls:
    - hosts:
        - "centerionware.com"
        - "*.centerionware.com"
      secretName: centerionware-default
