apiVersion: v1
kind: Service
metadata:
  name: mail-routing
  namespace: homelab
spec:
  type: ExternalName
  externalName: iredmail-pro.centerionware.lan
  ports:
  - port: 25
    targetPort: 25
    name: smtp
  - port: 110
    targetPort: 110
    name: pop3
  - port: 143
    targetPort: 143
    name: imap
  - port: 443
    targetPort: 443
    name: https
  - port: 465
    targetPort: 465
    name: smtps
  - port: 587
    targetPort: 587
    name: submission
  - port: 993
    targetPort: 993
    name: imaps
  - port: 995
    targetPort: 995
    name: pop3s
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    kubernetes.io/ingress.class: traefik
    #traefik.ingress.kubernetes.io/router.middlewares: homelab-authentik@kubernetescrd # Optional
  name: mail-ingress
  namespace: homelab
spec:
  ingressClassName: traefik
  rules:
    - host: "mail.centerionware.com"
      http:
        paths:
          - backend:
              service:
                name: mail-routing
                port:
                  number: 443
            path: / #Example.
            pathType: Prefix
    - host: "autoconfig.centerionware.com"
      http:
        paths:
          - backend:
              service:
                name: mail-routing
                port:
                  number: 443
            path: / #Example.
            pathType: Prefix
  tls:
    - hosts:
        - "centerionware.com"
        - "*.centerionware.com"
      secretName: centerionware-default

  smtp:
    expose:
      default: true
    exposedPort: 25
    port: 25
    protocol: TCP
  pop3:
    expose:
      default: true
    exposedPort: 110
    port: 110
    protocol: TCP
  imap:
    expose:
      default: true
    exposedPort: 143
    port: 143
    protocol: TCP
  smtps:
    expose:
      default: true
    exposedPort: 465
    port: 465
    protocol: TCP
  submission:
    expose:
      default: true
    exposedPort: 587
    port: 587
    protocol: TCP
  imaps:
    expose:
      default: true
    exposedPort: 993
    port: 993
    protocol: TCP
  pop3s:
    expose:
      default: true
    exposedPort: 995
    port: 995
    protocol: TCP



apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroutetcp-smtp
spec:
  entryPoints:
    - smtp
  routes:
  - match: HostSNI(`*`)
    priority: 10
    services:
    - name: mail-routing
      port: 25
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroutetcp-pop3
spec:
  entryPoints:
    - pop3
  routes:
  - match: HostSNI(`*`)
    priority: 10
    services:
    - name: mail-routing
      port: 110

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroutetcp-imap
spec:
  entryPoints:
    - imap
  routes:
  - match: HostSNI(`*`)
    priority: 10
    services:
    - name: mail-routing
      port: 143
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroutetcp-smtps
spec:
  entryPoints:
    - smtps
  routes:
  - match: HostSNI(`*`)
    priority: 10
    services:
    - name: mail-routing
      port: 465
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroutetcp-submission
spec:
  entryPoints:
    - submission
  routes:
  - match: HostSNI(`*`)
    priority: 10
    services:
    - name: mail-routing
      port: 587
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroutetcp-imaps

spec:
  entryPoints:
    - imaps
  routes:
  - match: HostSNI(`*`)
    priority: 10
    services:
    - name: mail-routing
      port: 993
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroutetcp-pop3s
spec:
  entryPoints:
    - pop3s
  routes:
  - match: HostSNI(`*`)
    priority: 10
    services:
    - name: mail-routing
      port: 995



  tls:    [17]
    secretName: supersecret       # [18]
    options:  [19]
      name: opt [20]
      namespace: default [21]
    certResolver: foo   [22]
    domains:  [23]
    - main: example.net [24]
      sans:   [25]
      - a.example.net
      - b.example.net
    passthrough: false  [26]