apiVersion: v1
kind: Service
metadata:
  name: middletest-service
  namespace: homelab
spec:
  type: ExternalName
  externalName: middletest.centerionware.lan
  ports:
  - name: http
    port: 805
    targetPort: 805
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    kubernetes.io/ingress.class: traefik
    # traefik.ingress.kubernetes.io/router.middlewares: homelab-authentik@kubernetescrd # Optional
  name: middletest-ingress
  namespace: homelab
spec:
  ingressClassName: traefik
  rules:
    - host: invoice-ninja.middletest.centerionware.com
      http:
        paths:
          - backend:
              service:
                name: middletest-service
                port:
                  number: 805
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "middletest.centerionware.com"
        - "*.middletest.centerionware.com"
      secretName: middletest-centerionware
