apiVersion: v1
kind: Service
metadata:
  name: prestashop-danny-service
  namespace: homelab
spec:
  type: ExternalName
  externalName: danny.centerionware.lan
  ports:
  - name: http
    port: 8116
    targetPort: 8116
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    kubernetes.io/ingress.class: traefik
  name: prestashop-danny-ingress
  namespace: homelab
spec:
  ingressClassName: traefik
  rules:
    - host: prestashop.danny.centerionware.com
      http:
        paths:
          - backend:
              service:
                name: prestashop-danny-service
                port:
                  number: 8116
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "danny.centerionware.com"
        - "*.danny.centerionware.com"
      secretName: danny-centerionware
