apiVersion: v1
kind: Service
metadata:
  name: jarvis-register-ai-service
  namespace: homelab
spec:
  type: ExternalName
  externalName: jarviscontroller.centerionware.lan
  ports:
  - name: http
    port: 5000
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    kubernetes.io/ingress.class: traefik
  name: jarvis-register-ai-ingress
  namespace: homelab
spec:
  ingressClassName: traefik
  rules:
    - host: register.jarvis.ai.centerionware.com
      http:
        paths:
          - backend:
              service:
                name: jarvis-register-ai-service
                port:
                  number: 5000
            path: / #Example.
            pathType: Prefix
  tls:
    - hosts:
        - "register.jarvis.ai.centerionware.com"
      secretName: jarvis-ai-secret
