apiVersion: v1
kind: Service
metadata:
  name: coturn-service
  namespace: homelab
spec:
  type: ExternalName
  externalName: rancher.centerionware.lan
  ports:
  - name: http
    port: 8081
    targetPort: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    kubernetes.io/ingress.class: traefik
  name: rancher-ingress
  namespace: homelab
spec:
  ingressClassName: traefik
  rules:
    - host: rancher.centerionware.com
      http:
        paths:
          - backend:
              service:
                name: coturn-service
                port:
                  number: 8081
            path: / #Example.
            pathType: Prefix
  tls:
    - hosts:
        - centerionware.com
        - '*.centerionware.com'
      secretName: centerionware-default
