apiVersion: v1
kind: Service
metadata:
  name: vpn-service
  namespace: homelab
spec:
  type: ExternalName
  externalName: vpn.centerionware.lan
  ports:
  - name: http
    port: 51820
    targetPort: 51820
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-issuer
    kubernetes.io/ingress.class: traefik
  name: vpn-ingress
  namespace: homelab
spec:
  ingressClassName: traefik
  rules:
    - host: vpn.centerionware.com
      http:
        paths:
          - backend:
              service:
                name: vpn-service
                port:
                  number: 51820
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - "centerionware.com"
        - "*.centerionware.com"
      secretName: centerionware-default
