{{- range .Values.certificates }}
  {{- $certNamespace := default $.Release.Namespace .namespace }}
  {{- $certSecretName := .secretName }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: {{ $certNamespace }}
spec:
  secretName: {{ $certSecretName }}
  {{- if and .reflectionAllowedNamespaces (kindIs "slice" .reflectionAllowedNamespaces) }}
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflectionAllowedNamespaces: {{ join "," .reflectionAllowedNamespaces }}
  {{- end }}
  issuerRef:
    name: {{ .issuerRef.name }}
    kind: {{ .issuerRef.kind }}
  commonName: {{ .commonName }}
  dnsNames:
{{- range .dnsNames }}
    - {{ . | quote }}
{{- end }}
---
{{- if .createReflectedSecrets }}
  {{- range .createReflectedSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
  namespace: {{ .namespace }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/ignore-differences: |
      jsonPointers:
      - /data
    reflector.v1.k8s.emberstack.com/reflects: "{{ $certNamespace }}/{{ $certSecretName }}"
type: Opaque
data: {}
  {{- end }}
{{- end }}
{{- end }}
