{{- $defaultEntryPoints := .Values.global.default_entrypoints }}

{{- range .Values.ingressRoutes }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .name }}
  namespace: {{ default $.Release.Namespace .namespace }}
spec:
  entryPoints:
  {{- range $defaultEntryPoints }}
    - {{ . }}
  {{- end }}
  {{- if .entrypoints }}
  {{- range .entrypoints }}
    - {{ . }}
  {{- end }}
  {{- end }}
  routes:
  {{- range .routes }}
    - kind: Rule
      match: {{ .match | quote }}
      services:
      {{- range .services }}
        - name: {{ .name }}
          port: {{ .port }}
          {{- if .passHostHeader }}
          passHostHeader: true
          {{- end }}
          {{- if .insecureSkipVerify }}
          serversTransport: {{ printf "%s-%s-transport" $.Release.Namespace .name  }}@kubernetescrd
          {{- end }}
          scheme: {{ default "http" .scheme }}
      {{- end }}
      middlewares:
      {{- range .middlewares }}
        {{- if kindIs "map" . }}
        - name: {{ .name }}
          namespace: {{ default $.Release.Namespace .namespace }}
        {{- else }}
        - name: {{ . }}
          namespace: {{ $.Release.Namespace }}
        {{- end }}
      {{- end }}
  {{- end }}
  {{- if .tls }}
  tls:
    secretName: {{ .tls.secretName }}
    {{- if .tls.domains }}
    domains:
      {{- range .tls.domains }}
      - main: {{ .main | quote }}
        {{- if .sans }}
        sans:
          {{- range .sans }}
          - {{ . | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
---  
{{- end }}