{{- $defaultEntryPoints := .Values.global.default_entrypoints }}

{{- range .Values.ingressRoutes }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .name }}
  namespace: {{ default $.Release.Namespace .namespace }}
spec:
  entryPoints:
  {{- range $defaultEntryPoints }}
    - {{ . }}
  {{- end }}
  {{- if .entrypoints }}
  {{- range .entrypoints }}
    - {{ . }}
  {{- end }}
  {{- end }}
  routes:
  {{- range .routes }}
    - kind: Rule
      match: {{ .match | quote }}
      services:
      {{- range .services }}
        - name: {{ .name }}
          port: {{ .port }}
          {{- if .insecureSkipVerify }}
          serversTransport: {{ printf "%s-transport" .name }}
          {{- end }}
      {{- end }}
      middlewares:
      {{- range .middlewares }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
  {{- end }}
  {{- if .tlsSecret }}
  tls:
    secretName: {{ .tlsSecret }}
  {{- end }}
{{- end }}