{{- $services := dict -}}

{{- /* Helper to add service port with ingressName */ -}}
{{- define "addPort" -}}
  {{- $svcMap := index . 0 -}}
  {{- $ns := index . 1 -}}
  {{- $svc := index . 2 -}}        {{/* service dict from values */}}
  {{- $ingressName := index . 3 -}} {{/* ingress or ingressRoute name */}}
  {{- $key := printf "%s/%s" $ns $svc.name }}

  {{- if not (hasKey $svcMap $key) }}
    {{- $_ := set $svcMap $key (dict "name" $svc.name "namespace" $ns "externalName" $svc.externalName "ports" (list)) }}
  {{- end }}

  {{- $existingSvc := index $svcMap $key }}
  {{- $ports := get $existingSvc "ports" }}

  {{- $exists := false }}
  {{- range $p := $ports }}
    {{- if and (eq $p.port $svc.port) (eq $p.targetPort $svc.targetPort) (eq $p.name $ingressName) }}
      {{- $exists = true }}
    {{- end }}
  {{- end }}

  {{- if not $exists }}
    {{- $ports = append $ports (dict "port" $svc.port "targetPort" $svc.targetPort "name" $ingressName) }}
    {{- $_ := set $existingSvc "ports" $ports }}
    {{- $_ := set $svcMap $key $existingSvc }}
  {{- end }}
{{- end }}

{{- /* Collect from ingressRoutes */ -}}
{{- range .Values.ingressRoutes }}
  {{- $ns := default $.Release.Namespace .namespace }}
  {{- $ingressName := .name }}
  {{- range .routes }}
    {{- range .services }}
        {{- include "addPort" (list $services $ns . $ingressName) }}
    {{- end }}
  {{- end }}
{{- end }}

{{- /* Collect from classicIngresses */ -}}
{{- range .Values.classicIngresses }}
  {{- $ns := default $.Release.Namespace .namespace }}
  {{- $ingressName := .name }}
  {{- range .services }}
      {{- include "addPort" (list $services $ns . $ingressName) }}
  {{- end }}
{{- end }}

{{- /* Render services */ -}}
{{- range $key, $svc := $services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svc.name }}
  namespace: {{ $svc.namespace }}
spec:
  type: ExternalName
  externalName: {{ $svc.externalName }}
  ports:
    {{- range $svc.ports }}
    - name: {{ .name | trimSuffix "-" | lower }}  # Kubernetes port names max 15 chars, no trailing dash
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}

{{- end }}