{{- $transports := dict -}}

{{- range .Values.ingressRoutes }}
  {{- $ns := default $.Release.Namespace .namespace }}
  {{- $needsTransport := false }}
  {{- range .routes }}
    {{- range .services }}
      {{- if .insecureSkipVerify }}
        {{- $needsTransport = true }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if $needsTransport }}
    {{- $tname := printf "%s-insecureSkipVerify" $ns }}
    {{- if not (hasKey $transports $tname) }}
      {{- $_ := set $transports $tname (dict "name" $tname "namespace" $ns "insecureSkipVerify" true) }}
    {{- end }}
  {{- end }}
{{- end }}

{{- range $tname, $t := $transports }}
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{ $t.name }}
  namespace: {{ $t.namespace }}
spec:
  insecureSkipVerify: {{ $t.insecureSkipVerify }}
---
{{- end }}